WILKCONF="${WILKCONF:-${HOME}/wilkconf}"
BASHRC_DIR="${BASHRC_DIR:-${WILKCONF}/bashrc}"
if [[ -d "${BASHRC_DIR}" ]]; then
    for f in "${BASHRC_DIR}"/*; do
        if [[ "${f: -3:3}" == ".sh" ]]; then
            source "${f}"
        elif [[ -x "${f}" ]]; then
            ${f}
        fi
    done
fi
