
(setq org-caldav-url "https://rackermail.cannot.name/users")
(setq org-caldav-inbox "/home/will/doc/org/agenda/caldav.org")
(setq org-caldav-files '("/home/will/doc/org/agenda/agenda.org"))
(setq org-caldav-calendar-id "william.kelly%40rackspace.com/calendar")
(setq org-caldav-uuid-extension ".EML")
(setq org-import-icalendar-filename  org-caldav-inbox)
(setq org-agenda-files '("/home/will/doc/org/agenda/"))
;(setq org-caldav-sync-changes-to-org 'all)
;(setq org-icalendar-timezone "america/chicago")
